content:
  - filePath: './path/to/markdown-1.md'
    title: Markdown 1
    pageId: '353468432'
    contentType: page
    labels:
      - ci/cd
  - filePath: './path/to/markdown-2.md'
    title: Markdown 2
    pageId: '353435649'
    contentType: page
    labels:
      - ci/cd
