name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  app-name: 'confluence-updater'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  build-linux:
    runs-on: ubuntu-latest
    needs: rustfmt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Binary
      #     path: |
      #       ${{ steps.compile.outputs.BUILT_ARCHIVE }}
      #       ${{ steps.compile.outputs.BUILT_CHECKSUM }}
